
font_family      family='Iosevka'              style=Regular
bold_font        family='Iosevka Slab'         style=SemiBold
bold_italic_font family='Monofur Nerd Font'    style=Regular
italic_font      family='UbuntuMono Nerd Font' style=Italic

background_opacity 0.9
font_size 14.0
remember_window_size  no
initial_window_width  120c
initial_window_height 32c
resize_in_steps yes
tab_bar_style hidden

include theme.conf
