
font_family      family='Iosevka'               style=Regular  features=''
bold_font        family='Iosevka Slab'          style=SemiBold features=''
bold_italic_font family='ProggyClean Nerd Font' style=Regular  features=''
italic_font      family='Iosevka Slab'          style=Italic   features=''

background_opacity 0.9
font_size 14.0
remember_window_size  no
initial_window_width  120c
initial_window_height 32c
resize_in_steps yes
tab_bar_style hidden


include theme.conf
