source = theme.conf

$alert = rgb($orange)
$bg_attention = rgb($dark5)
$bg_main = rgba($bgbf)
$bg_critical = rgb($red1)
$bg_hover = rgb($dark3)
$bg_widget = rgba($bg_dark40)
$bg_widget_r = rgb($green)
$border_main = rgb($bg)
$box_shadow = rgba($bg_highlight40)
$fg_attention = rgb($yellow)
$fg_attention_raw = $yellow
$fg_critical = rgb($blue6)
$fg_hover = rgb($gitchange)
$fg_widget = rgb($green)
$fg_widget_r = rgb($bg_dark)
$fg_dimmed = rgb($comment)
$fg_dimmed_raw = $comment
$fg_readonly = rgb($red)
$text_shadow1 = rgba($cyanbf)
$text_shadow2 = rgba($redbf)
