-- Los colores del señor lucho canaval jr.

local M = {}

local bg = "24283b"
local bg_dark = "1f2335"
-- local bg_dark1 = "1b1e2d"
local bg_highlight = "292e42"
local blue = "7aa2f7"
local blue0 = "3d59a1"
-- local blue1 = "2ac3de"
-- local blue2 = "0db9d7"
-- local blue5 = "89ddff"
local blue6 = "b4f9f8"
local blue7 = "394b70"
local comment = "565f89"
local cyan = "7dcfff"
local dark3 = "545c7e"
local dark5 = "737aa2"
-- local fg = "c0caf5"
-- local fg_dark = "a9b1d6"
-- local fg_gutter = "3b4261"
local green = "9ece6a"
-- local green1 = "73daca"
-- local green2 = "41a6b5"
-- local magenta = "bb9af7"
-- local magenta2 = "ff007c"
local orange = "ff9e64"
-- local purple = "9d7cd8"
local red = "f7768e"
local red1 = "db4b4b"
-- local teal = "1abc9c"
-- local terminal_black = "414868"
local yellow = "e0af68"
-- local gitadd = "449dab"
local gitchange = "6183bb"
-- local gitdelete = "914c54"

M.alert = "rgb(" .. orange .. ")"
M.bg_attention = "rgb(" .. dark5 .. ")"
M.bg_main = "rgba(" .. bg .. "bf)"
M.bg_critical = "rgb(" .. red1 .. ")"
M.bg_hover = "rgb(" .. dark3 .. ")"
M.bg_widget = "rgba(" .. bg_dark .. "40)"
M.bg_widget_r = "rgb(" .. green .. ")"
M.border0 = "rgba(" .. blue .. "80)"
M.border1 = "rgba(" .. blue0 .. "80)"
M.border2 = "rgba(" .. blue0 .. "40)"
M.border3 = "rgba(" .. blue7 .. "40)"
M.border_main = "rgb(" .. bg .. ")"
M.box_shadow = "rgba(" .. bg_highlight .. "40)"
M.fg_attention = "rgb(" .. yellow .. ")"
M.fg_attention_raw = yellow
M.fg_critical = "rgb(" .. blue6 .. ")"
M.fg_hover = "rgb(" .. gitchange .. ")"
M.fg_widget = "rgb(" .. green .. ")"
M.fg_widget_r = "rgb(" .. bg_dark .. ")"
M.fg_dimmed = "rgb(" .. comment .. ")"
M.fg_dimmed_raw = comment
M.fg_readonly = "rgb(" .. red .. ")"
M.text_shadow1 = "rgba(" .. cyan .. "bf)"
M.text_shadow2 = "rgba(" .. red .. "bf)"

return M
