source = $HOME/.config/hypr/colors.conf

$font = Orbitron

general {
	hide_cursor = false
	ignore_empty_input = true
}

background {
	monitor =
	path = screenshot
	blur_passes = 3
}

background {
    monitor = eDP-1
    path = /tmp/eDP-1-lockscreen.png
    color = rgb($bg)
}

background {
    monitor = HDMI-A-1
    path = /tmp/HDMI-A-1-lockscreen.png
    color = rgb($bg)
}

animations {
	enabled = true
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 5, linear
	animation = fadeOut, 1, 5, linear
	animation = inputFieldDots, 1, 2, linear
}

# face
image {
	monitor =
	path = $HOME/.face
	border_color = rgb($fg_widget)
	size = 128
	position = 96, 0
	halign = left
	valign = center
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

# password
input-field {
	monitor =
	capslock_color = rgb($warning)
	check_color = rgb($warning)
	fail_color = rgb($error)
	font_color = rgb($fg_widget)
	hide_input = true
	inner_color = rgb($bg_widget)
	outer_color = rgb($fg_widget)
	hide_input_base_color = rgb($fg_widget_r)
	fail_text = <i>$FAIL <b>($ATTEMPTS)</b> </i>
	placeholder_text = <span foreground="##$warning" size="x-large">󰌾</span>
	size = 96, 96
	position = 0, 0
	rounding = -1
	halign = center
	valign = center
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

# battery
label {
	monitor =
	text = cmd[update:10000] lbatstatus
	color = rgb($fg_widget)
	font_size = 25
	font_family = $font
	position = 20, -10
	halign = left
	valign = top
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

# binary clock
label {
	monitor =
	text = cmd[update:5000] lclock -o | sed -e 's/\r//g' | jq -r '.text'
	color = rgb($fg_widget)
	font_size = 25
	font_family = $font
	position = -20, -175
	halign = right
	valign = top
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

# date
label {
	monitor =
	text = cmd[update:60000] date +"󰃭  %A, %d %B %Y"
	color = rgb($fg_widget)
	font_size = 25
	font_family = $font
	position = -20, -10
	halign = right
	valign = top
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

# time
label {
	monitor =
	text =  $TIME
	color = rgb($fg_widget)
	font_size = 75
	font_family = $font
	position = -20, -50
	halign = right
	valign = top
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

# keyboard layout
label {
	monitor =
	text = 󰌌  $LAYOUT
	onclick = hyprctl switchxkblayout all next
	color = rgb($fg_widget)
	font_family = $font
	font_size = 25
	position = -20, 10
	halign = right
	valign = bottom
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

## Slow commands here.
# pacman updates
label {
	monitor =
	text = cmd[update:60000] echo "󰮯  $(checkupdates | wc -l) updates."
	color = rgb($fg_widget)
	font_size = 25
	font_family = $font
	position = 20, 10
	halign = left
	valign = bottom
	shadow_boost = 1.2
	shadow_color = rgba($accent88)
	shadow_passes = 3
	shadow_size = 4
}

