source = ~/.config/hypr/colors.conf

# coloring
accent = rgba($accentff)
accent_secondary = rgba($accent_altff)
alternate_base = rgba($bg_highlightdd)
background = rgba($bgdd)
base = rgba($bg_darkdd)
bright_text = rgba($fg_widgetff)
text = rgba($fgff)

# fonts
font_size = 12
h1_size = 20
h2_size = 16
h3_size = 14
small_font_size = 10

# icons
icon_theme = Reversal-dark

# vim: set ts=4 sw=4 et sts=0 :
