add_newline = false
format = """
$character\
$status\
$memory_usage\
$jobs\
$cmd_duration\
$conda\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmake\
$golang\
$julia\
$nodejs\
$python\
$rust\
$lua\
$username\
$hostname\
$directory"""

[character]
format         = "$symbol"
error_symbol   = "[❯](red)"
success_symbol = "[❯](white)"
vicmd_symbol   = "[❮](yellow)"

[cmake]
format = "[$symbol($version )]($style)"
style  = "blue"

[cmd_duration]
format            = "[ $duration]($style) "
min_time          = 2_500
show_milliseconds = true
style             = "yellow"

[conda]
format = "[$symbol$environment]($style) "
style  = "purple"
symbol = "◯ "

[directory]
format            = "[$path]($style)"
home_symbol       = " "
read_only         = " "
style             = "bright-blue"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "
style  = "bright-purple"
symbol = " "

[git_commit]
style = "bright-purple"

[git_state]
style = "bright-purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style  = "bright-purple"

[golang]
format = "[$symbol($version )]($style)"
style  = "cyan"
symbol = " "

[hostname]
format   = "[$hostname]($style):"
ssh_only = false
style    = "green"

[jobs]
style = "blue"

[julia]
format = "[$symbol($version )]($style)"
style  = "cyan"

[lua]
format = "[$symbol($version )]($style)"
style  = "cyan"
symbol = " "

[memory_usage]
format = "$symbol [${ram}( \\| ${swap})]($style) "
style  = "white"

[nodejs]
format = "[$symbol($version )]($style)"
style  = "cyan"

[python]
format = "[$symbol($version )]($style)"
style  = "cyan"
symbol = " "

[rlang]
format = "[$symbol($version )]($style)"
style  = "cyan"

[rust]
format = "[$symbol($version )]($style)"
style  = "cyan"
symbol = " "

[status]
disabled = false

[username]
format      = "[$user]($style)@"
show_always = true
style_root  = "red"
style_user  = "green"

[kotlin]
disabled = true
[kubernetes]
disabled = true
[line_break]
disabled = true
[aws]
disabled = true
[battery]
disabled = true
[crystal]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[env_var]
disabled = true
[erlang]
disabled = true
[gcloud]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[hg_branch]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[ocaml]
disabled = true
[openstack]
disabled = true
[package]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[red]
disabled = true
[ruby]
disabled = true
[scala]
disabled = true
[shell]
[shlvl]
[singularity]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[time]
[vagrant]
disabled = true
[vlang]
disabled = true
[vcsh]
disabled = true
[zig]
disabled = true

