ConfigFile = '/home/lmcs/.config/lazysql/config.toml'
LocalConfigFile = ''

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100
TreeWidth = 30
JSONViewerWordWrap = false
EnterOpensJSONViewer = false
ConfirmOnQuit = true

[[database]]
Name = 'Horus DB'
URL = 'postgresql://pgdev:change_pg_pwd@localhost:5432/horus?sslmode=disable'
Provider = 'postgres'
DBName = 'horus'
