skip_selection = true

[env]
ENV_VARIABLE = "lol we logged in nicely huh!"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Adwaita"
cursor_blink = true
font_name = "Sixtyfour 14"
icon_theme_name = "Reversal-dark"
theme_name = "Adwaita-dark"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[appearance]
greeting_msg = "Salutations, earthling!"

[widget.clock]
format = "%A, %e of %B %R"
resolution = "500ms"
timezone = "America/Chicago"
label_width = 150
