AddPackage accountsservice
AddPackage amd-ucode
AddPackage base
AddPackage dosfstools
AddPackage efibootmgr
AddPackage fish
AddPackage gptfdisk
AddPackage grml-zsh-config
AddPackage linux
AddPackage linux-firmware
AddPackage linux-headers
AddPackage networkmanager
AddPackage ntp
AddPackage openslide
AddPackage openssh
AddPackage pacman-contrib
AddPackage pacquery
AddPackage parallel
AddPackage pkgstats
AddPackage powertop
AddPackage socat
AddPackage sshfs
AddPackage zsh
