AddPackage base-devel
AddPackage clang
AddPackage cmake
AddPackage docker
AddPackage docker-buildx
AddPackage docker-compose
AddPackage git
AddPackage github-cli
AddPackage glfw
AddPackage hyperfine
AddPackage lazydocker
AddPackage lazygit
AddPackage luarocks
AddPackage neovim
AddPackage npm
AddPackage tokei
AddPackage tree-sitter-cli
AddPackage uv
